/**:
  comunication:
    rc_handler:
      ros__parameters:
        # home: [37.307689, -5.940203, 85.37814771871618] #Lago de la vida Grande
        # home: [37.3047028, -5.9404694, 85.37814771871618] #Lago de la vida Pequeño
        # home: [37.3088513, -5.9398486, 85.37814771871618] #Lago de la vida Alto
        # home: [37.4191583,  -5.99902, 63.49701432163044] #Lago de Alamillo Izq
        # home: [37.4190694, -5.9984778, 63.49701432163044] #Lago de Alamillo Der
        # home: [37.34078913574364,  -6.023647754208303, 63.49701432163044] # Gelves Port
        home: [37.33788935, -5.85732761, 63.49701432163044] # Rio Guadaria
    ref_llc:
      ros__parameters:
        reference_mode: True     #False sin mode and True lineal mode
    ref_mlc:
      ros__parameters:
        Dis_ref: True     #Referencia por escalones o continua
    ref_hlc:
      ros__parameters:
        Dis_ref: True     #Referencia por escalones o continua
  control:
    filter_hlc:
      ros__parameters:
        Ts: 100.0     #Tiempo de muestreo Filtro
        tau_f: 0.2  #Cosntante de tiempo filtro
    
